### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by noharass** [luzhixing12345/paperplotlib#2]
使用IDLE运行快速开始的代码后报错:
Traceback (most recent call last):
  File "...\paperplotlib.py", line 1, in <module>
    import paperplotlib as ppl
  File "...\paperplotlib.py", line 10, in <module>
    graph = ppl.BarGraph()
AttributeError: partially initialized module 'paperplotlib' has no attribute 'BarGraph' (most likely due to a circular import)

**Comment by JayYoung2021** [comment]
请将快速开始的代码的文件的名称从 `paperplotlib.py` 更换为其他名字，例如 `main.py`，否则在 `import paperplotlib` 时，Python 会优先查找本地的 paperplotlib，即代码本身，最终造成循环引用。

可以尝试创建一个内容为 `import foobar` 同时文件名为 `foobar.py` 的 Python 文件，也会出现类似的问题。
